name: Build and run Horusec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crm-cavalcante:frontend
  horusec:
    runs-on: ubuntu-latest
    steps:
    - name: Instalar Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      # Certifique-se de que o Docker seja instalado antes de prosseguir

    - name: Instalar Horusec CLI
      run: |
        curl -fsSL https://github.com/ZupIT/horusec/releases/latest/download/install.sh -o install.sh
        chmod +x install.sh
        ./install.sh --version latest
      # Certifique-se de que o Horusec CLI seja instalado antes de prosseguir

    - name: Executar análise de segurança com Horusec
      run: horusec start
